version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Install npm
          command: |
            npm install
            ls -l
      - run:
          name: Install AWS cli
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: AWS configure
          command: |
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set default.region ${AWS_REGION}
      - run:
          name: Install aws dependencies
          command: |
            sudo apt-get install -y less && sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Showing files in folder
          command: ls -l
      - run:
          name: Zip up files
          command: |
            zip -r lambda.zip index.js node_modules/
      - run:
          name: Update zip in lambda function
          command: >
            aws lambda update-function-code 
            --region=${AWS_REGION}
            --function-name=EmailSender  
            --zip-file fileb://lambda.zip

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
